gui:
  theme:
    activeBorderColor:
      - '#89b4fa' # Blue
      - bold
    inactiveBorderColor:
      - '#a6adc8' # Surface0
    optionsTextColor:
      - '#89b4fa' # Blue
    selectedLineBgColor:
      - '#313244' # Surface0
    cherryPickedCommitBgColor:
      - '#45475a' # Surface1
    cherryPickedCommitFgColor:
      - '#89b4fa' # Blue
    unstagedChangesColor:
      - '#f38ba8' # Red
    defaultFgColor:
      - '#cdd6f4' # Text
    searchingActiveBorderColor:
      - '#f9e2af' # Yellow

  authorColors:
    '*': '#b4befe'

